language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
env:
  global:
    - BUILD_DIR_NAME=build
    - DOC_BRANCH=release
    # COVERITY_SCAN_TOKEN
    - secure: "GjN2rHGtPPXTMwWUzpB9ULqDrFXmShysGtQ8VIXYJULUUHZ26entYWuwTb8q3NI8syVeDFyCmam7PSnRgc/nuaOBh8/2lO+dAB1H54jfvbREBBYC2yIIZAT1z/oQ/ZYWdJBrWsNw+pPYk8lY1Z52ggLu2Gd4fktrzuISch7CuCY="
  matrix:
    - LANG=CPP LIB_LOW_LEVEL_API=ON PUBLISH_DOCS=ON PUBLISH_COVERITY_SCAN=ON
    - LANG=CPP LIB_LOW_LEVEL_API=OFF
    - LANG=PHP LIB_LOW_LEVEL_API=ON
    - LANG=PHP LIB_LOW_LEVEL_API=OFF
cache:
  directories:
    - $HOME/cmake
    - $HOME/swig
    - $HOME/phpunit
    - $HOME/doxygen
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcurl4-openssl-dev
      - python-yaml
      - php5
      - php5-dev
      - php5-cli
      - graphviz
before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-swig.sh
  - bash ./ci/install-phpunit.sh
  - bash ./ci/install-credentials.sh
  - bash ./ci/install-doxygen.sh
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
after_success:
  - bash ./ci/publish-docs.sh
sudo: false
