language: cpp
compiler:
  - clang
  - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y swig
    - sudo apt-get install -y python-yaml
    - sudo apt-get install -y php5
    - sudo apt-get install -y phpunit
before_script:
    - mkdir build
    - cd build
    - cmake -DPLATFORM_NAME=PHP ..
script: make && ctest --verbose
