language: cpp
compiler:
  - gcc
#  - clang
os:
  - linux
env:
  global:
    - BUILD_DIR_NAME=build
    - DOC_BRANCH=master
    # COVERITY_SCAN_TOKEN
    - secure: "GjN2rHGtPPXTMwWUzpB9ULqDrFXmShysGtQ8VIXYJULUUHZ26entYWuwTb8q3NI8syVeDFyCmam7PSnRgc/nuaOBh8/2lO+dAB1H54jfvbREBBYC2yIIZAT1z/oQ/ZYWdJBrWsNw+pPYk8lY1Z52ggLu2Gd4fktrzuISch7CuCY="
  matrix:
    - LANG=cpp LIB_LOW_LEVEL_API=ON PUBLISH_DOCS=ON PUBLISH_COVERITY_SCAN=ON
    - LANG=php LIB_LOW_LEVEL_API=ON
cache:
  directories:
    - $HOME/cmake
    - $HOME/swig
    - $HOME/phpunit
    - $HOME/doxygen
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - libcurl4-openssl-dev
      - g++-6
#      - clang-3.6
      - php5
      - php5-dev
      - php5-cli
      - graphviz
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-swig.sh
  - bash ./ci/install-phpunit.sh
  - bash ./ci/install-credentials.sh
  - bash ./ci/install-doxygen.sh
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
after_success:
  - bash ./ci/publish-docs.sh
sudo: false
