language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
env:
  global:
    - BUILD_DIR_NAME=build
  matrix:
    - PLATFORM_NAME=CPP LIB_LOW_LEVEL_API=ON PUBLISH_DOCS=ON
    - PLATFORM_NAME=CPP LIB_LOW_LEVEL_API=OFF
    - PLATFORM_NAME=PHP LIB_LOW_LEVEL_API=ON
    - PLATFORM_NAME=PHP LIB_LOW_LEVEL_API=OFF
cache:
  directories:
    - $HOME/cmake
    - $HOME/swig
    - $HOME/phpunit
    - $HOME/doxygen
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.9
      - clang-3.6
      - libcurl4-openssl-dev
      - python-yaml
      - php5
      - php5-dev
      - php5-cli
      - graphviz
before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-swig.sh
  - bash ./ci/install-phpunit.sh
  - bash ./ci/install-credentials.sh
  - bash ./ci/install-doxygen.sh
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6"; fi
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
after_success:
  - bash ./ci/publish-docs.sh
sudo: false
