language: cpp
sudo: false

env:
  global:
    - BUILD_DIR_NAME=build
    - DOC_BRANCH=master
    # COVERITY_SCAN_TOKEN
    - secure: "GjN2rHGtPPXTMwWUzpB9ULqDrFXmShysGtQ8VIXYJULUUHZ26entYWuwTb8q3NI8syVeDFyCmam7PSnRgc/nuaOBh8/2lO+dAB1H54jfvbREBBYC2yIIZAT1z/oQ/ZYWdJBrWsNw+pPYk8lY1Z52ggLu2Gd4fktrzuISch7CuCY="

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libcurl4-openssl-dev
            - php5
            - php5-dev
            - php5-cli
            - graphviz
      env:
        global:
          - COMPILER=g++-4.9
        matrix:
          - LANG=cpp LIB_LOW_LEVEL_API=ON PUBLISH_DOCS=ON PUBLISH_COVERITY_SCAN=ON
          - LANG=cpp LIB_LOW_LEVEL_API=OFF
          - LANG=php LIB_LOW_LEVEL_API=ON
          - LANG=php LIB_LOW_LEVEL_API=OFF
cache:
  directories:
    - $HOME/cmake
    - $HOME/swig
    - $HOME/phpunit
    - $HOME/doxygen
before_install:
  - bash ./ci/install-cmake.sh
  - bash ./ci/install-swig.sh
  - bash ./ci/install-phpunit.sh
  - bash ./ci/install-credentials.sh
  - bash ./ci/install-doxygen.sh
before_script:
  - bash ./ci/configure.sh
script:
  - bash ./ci/run.sh
after_success:
  - bash ./ci/publish-docs.sh
