language: cpp
compiler:
  - clang
  - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y swig
    - sudo apt-get install -y python-yaml
before_script:
    - mkdir build
    - cd build
    - cmake -DBUILD_CPP_PROGRAMS=YES ..
script: make
